### ISSUE TITLE
查询向量数据库就报找不到index

### ISSUE THREAD

**Issue by xgwangdl** [qifan777/dive-into-spring-ai#6]
2024-12-18T20:59:07.106+08:00 ERROR 5908 --- [knowledge-base] [nio-9902-exec-4] i.g.q.k.i.config.GlobalExceptionAdvice   : 系统异常

redis.clients.jedis.exceptions.JedisDataException: default-index: no such index
	at redis.clients.jedis.Protocol.processError(Protocol.java:105) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:162) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:221) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.getOne(Connection.java:333) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.Connection.executeCommand(Connection.java:138) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:24) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244) ~[jedis-5.0.2.jar:na]
	at redis.clients.jedis.UnifiedJedis.ftSearch(UnifiedJedis.java:3688) ~[jedis-5.0.2.jar:na]
	at org.springframework.ai.vectorstore.RedisVectorStore.doSimilaritySearch(RedisVectorStore.java:377) ~[spring-ai-redis-store-1.0.0-M2.jar:1.0.0-M2]
	at org.springframework.ai.vectorstore.observation.AbstractObservationVectorStore.lambda$similaritySearch$5(AbstractObservationVectorStore.java:85) ~[spring-ai-core-1.0.0-M2.jar:1.0.0-M2]
	at io.micrometer.observation.Observation.observe(Observation.java:565) ~[micrometer-observation-1.12.1.jar:1.12.1]
	at org.springframework.ai.vectorstore.observation.AbstractObservationVectorStore.similaritySearch(AbstractObservationVectorStore.java:84) ~[spring-ai-core-1.0.0-M2.jar:1.0.0-M2]
	at io.github.qifan777.knowledge.demo.MessageDemoController.chatStreamWithDatabase(MessageDemoController.java:120) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

**Comment by IAMEMEM** [comment]
在ai里面配置    vectorstore:
       redis:
         initialize-schema: true
